'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Akashic_Records_of_Teyvat.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Archaic_Feather_of_Jagged_Peaks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Archaic_Feather_of_Jagged_Peaks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Archaic_Flower_of_Creviced_Cliff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Archaic_Flower_of_Creviced_Cliff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Archaic_Goblet_of_Chiseled_Crag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Archaic_Goblet_of_Chiseled_Crag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Archaic_Mask_of_Solitude_Basalt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Archaic_Mask_of_Solitude_Basalt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Archaic_Sundial_of_Enduring_Jade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Archaic_Sundial_of_Enduring_Jade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Blizzard_Broken_Rime_s_Echo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Blizzard_Broken_Rime_s_Echo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Blizzard_Frost_Weaved_Dignity() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Blizzard_Frost_Weaved_Dignity", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Blizzard_Frozen_Homeland_s_Demise() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Blizzard_Frozen_Homeland_s_Demise", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Blizzard_Icebreaker_s_Resolve() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Blizzard_Icebreaker_s_Resolve", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Blizzard_Snowswept_Memory() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Blizzard_Snowswept_Memory", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Bloodstained_Black_Plume() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Bloodstained_Black_Plume", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Bloodstained_Chevalier_s_Goblet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Bloodstained_Chevalier_s_Goblet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Bloodstained_Final_Hour() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Bloodstained_Final_Hour", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Bloodstained_Flower_of_Iron() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Bloodstained_Flower_of_Iron", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Bloodstained_Iron_Mask() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Bloodstained_Iron_Mask", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Gladiator_s_Destiny() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Gladiator_s_Destiny", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Gladiator_s_Intoxication() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Gladiator_s_Intoxication", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Gladiator_s_Longing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Gladiator_s_Longing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Gladiator_s_Nostalgia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Gladiator_s_Nostalgia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Gladiator_s_Triumphus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Gladiator_s_Triumphus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Heart_Copper_Compass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Heart_Copper_Compass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Heart_Gilded_Corsage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Heart_Gilded_Corsage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Heart_Goblet_of_Thundering_Deep() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Heart_Goblet_of_Thundering_Deep", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Heart_Gust_of_Nostalgia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Heart_Gust_of_Nostalgia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Heart_Wine_Stained_Tricorne() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Heart_Wine_Stained_Tricorne", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Lavawalker_s_Epiphany() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Lavawalker_s_Epiphany", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Lavawalker_s_Resolution() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Lavawalker_s_Resolution", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Lavawalker_s_Salvation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Lavawalker_s_Salvation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Lavawalker_s_Torment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Lavawalker_s_Torment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Lavawalker_s_Wisdom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Lavawalker_s_Wisdom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Maiden_s_Distant_Love() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Maiden_s_Distant_Love", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Maiden_s_Fading_Beauty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Maiden_s_Fading_Beauty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Maiden_s_Fleeting_Leisure() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Maiden_s_Fleeting_Leisure", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Maiden_s_Heart_stricken_Infatuation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Maiden_s_Heart_stricken_Infatuation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Maiden_s_Passing_Youth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Maiden_s_Passing_Youth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Royal_Flora() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Royal_Flora", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Royal_Masque() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Royal_Masque", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Royal_Plume() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Royal_Plume", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Royal_Pocket_Watch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Royal_Pocket_Watch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Royal_Silver_Urn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Royal_Silver_Urn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Summer_Night_s_Bloom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Summer_Night_s_Bloom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Summer_Night_s_Finale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Summer_Night_s_Finale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Summer_Night_s_Mask() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Summer_Night_s_Mask", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Summer_Night_s_Moment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Summer_Night_s_Moment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Summer_Night_s_Waterballoon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Summer_Night_s_Waterballoon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Thundering_Hourglass_of_Thunder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Thundering_Hourglass_of_Thunder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Thundering_Omen_of_Thunderstorm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Thundering_Omen_of_Thunderstorm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Thundering_Survivor_of_Catastrophe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Thundering_Survivor_of_Catastrophe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Thundering_Thunder_Summoner_s_Crown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Thundering_Thunder_Summoner_s_Crown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Thundering_Thunderbird_s_Mercy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Thundering_Thunderbird_s_Mercy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Thundersoother_s_Diadem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Thundersoother_s_Diadem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Thundersoother_s_Goblet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Thundersoother_s_Goblet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Thundersoother_s_Heart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Thundersoother_s_Heart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Thundersoother_s_Hour_of_Soothing_Thunder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Thundersoother_s_Hour_of_Soothing_Thunder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Thundersoother_s_Plume() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Thundersoother_s_Plume", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Viridescent_Arrow_Feather() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Viridescent_Arrow_Feather", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Viridescent_In_Remembrance_of_Viridescent_Fields() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Viridescent_In_Remembrance_of_Viridescent_Fields", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Viridescent_Venerer_s_Determination() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Viridescent_Venerer_s_Determination", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Viridescent_Venerer_s_Diadem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Viridescent_Venerer_s_Diadem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Viridescent_Venerer_s_Vessel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Viridescent_Venerer_s_Vessel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Wander_s_Arrow_Feather() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Wander_s_Arrow_Feather", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Wanderer_s_Dawnlight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Wanderer_s_Dawnlight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Wanderer_s_Final_Hour() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Wanderer_s_Final_Hour", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Wanderer_s_String_Kettle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Wanderer_s_String_Kettle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Wanderer_s_Top_Hat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Wanderer_s_Top_Hat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Witch_s_End_Time() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Witch_s_End_Time", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Witch_s_Ever_Burning_Plume() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Witch_s_Ever_Burning_Plume", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Witch_s_Flower_of_Blaze() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Witch_s_Flower_of_Blaze", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Witch_s_Heart_Flames() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Witch_s_Heart_Flames", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artifact_Witch_s_Scorching_Hat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artifact_Witch_s_Scorching_Hat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Character_Albedo_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character_Albedo_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Character_Amber_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character_Amber_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Character_Barbara_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character_Barbara_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Character_Beidou_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character_Beidou_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Character_Bennett_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character_Bennett_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Character_Chongyun_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character_Chongyun_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Character_Diluc_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character_Diluc_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Character_Diona_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character_Diona_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Character_Fischl_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character_Fischl_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Character_Ganyu_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character_Ganyu_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Character_Jean_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character_Jean_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Character_Kaeya_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character_Kaeya_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Character_Keqing_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character_Keqing_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Character_Klee_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character_Klee_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Character_Lisa_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character_Lisa_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Character_Mona_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character_Mona_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Character_Ningguang_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character_Ningguang_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Character_Noelle_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character_Noelle_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Character_Qiqi_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character_Qiqi_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Character_Razor_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character_Razor_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Character_Sucrose_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character_Sucrose_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Character_Tartaglia_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character_Tartaglia_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Character_Venti_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character_Venti_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Character_Xiangling_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character_Xiangling_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Character_Xiao_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character_Xiao_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Character_Xingqiu_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character_Xingqiu_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Character_Xinyan_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character_Xinyan_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Character_Zhongli_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Character_Zhongli_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Emblem_Liyue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Emblem_Liyue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Emblem_Mondstadt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Emblem_Mondstadt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_Albedo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_Albedo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_Amber() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_Amber", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_barbra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_barbra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_Beidou() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_Beidou", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_Bennet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_Bennet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_Chongyun() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_Chongyun", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_Diluc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_Diluc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_Diona() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_Diona", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_Fischl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_Fischl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_Ganyu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_Ganyu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_Jean() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_Jean", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_Keaya() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_Keaya", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_Keqing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_Keqing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_Klee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_Klee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_Lisa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_Lisa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_mcF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_mcF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_mcM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_mcM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_Mona() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_Mona", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_Ningguang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_Ningguang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_Noelle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_Noelle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_QiQi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_QiQi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_Razor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_Razor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_Sucrose() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_Sucrose", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_Tartaglia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_Tartaglia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_Venti() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_Venti", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_Xaio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_Xaio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_XiangLing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_XiangLing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_Xinqui() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_Xinqui", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_Xinyan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_Xinyan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property port_Zhongli() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("port_Zhongli", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Random_Adventure_Experience() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Random_Adventure_Experience", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Random_Character_Experience() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Random_Character_Experience", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Random_Item_Acquaint_Fate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Random_Item_Acquaint_Fate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Random_Item_Adventurer_s_Experience() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Random_Item_Adventurer_s_Experience", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Random_Item_Hero_s_Wit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Random_Item_Hero_s_Wit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Random_Item_Intertwined_Fate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Random_Item_Intertwined_Fate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Random_Item_Primogem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Random_Item_Primogem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Random_Item_Wanderer_s_Advice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Random_Item_Wanderer_s_Advice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Random_Liyue_Reputation_EXP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Random_Liyue_Reputation_EXP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Random_Mondstadt_Reputation_EXP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Random_Mondstadt_Reputation_EXP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Traveler_Female_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Traveler_Female_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Traveler_Male_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Traveler_Male_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Amos_Bow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Amos_Bow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Aquila_Favonia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Aquila_Favonia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Blackcliff_Agate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Blackcliff_Agate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Blackcliff_Longsword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Blackcliff_Longsword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Blackcliff_Pole() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Blackcliff_Pole", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Blackcliff_Slasher() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Blackcliff_Slasher", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Blackcliff_Warbow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Blackcliff_Warbow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Compound_Bow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Compound_Bow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Crescent_Pike() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Crescent_Pike", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Deathmatch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Deathmatch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Dragon_s_Bane() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Dragon_s_Bane", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Dragonspine_Spear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Dragonspine_Spear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Eye_of_Perception() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Eye_of_Perception", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Favonius_Codex() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Favonius_Codex", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Favonius_Greatsword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Favonius_Greatsword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Favonius_Lance() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Favonius_Lance", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Favonius_Sword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Favonius_Sword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Favonius_Warbow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Favonius_Warbow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Festering_Desire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Festering_Desire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Frostbearer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Frostbearer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Iron_Sting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Iron_Sting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Lion_s_Roar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Lion_s_Roar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Lost_Prayer_to_the_Sacred_Winds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Lost_Prayer_to_the_Sacred_Winds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Mappa_Mare() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Mappa_Mare", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Memory_of_Dust() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Memory_of_Dust", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Primordial_Jade_Winged_Spear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Primordial_Jade_Winged_Spear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Prototype_Amber() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Prototype_Amber", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Prototype_Archaic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Prototype_Archaic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Prototype_Crescent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Prototype_Crescent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Prototype_Rancour() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Prototype_Rancour", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Prototype_Starglitter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Prototype_Starglitter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Rainslasher() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Rainslasher", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Royal_Bow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Royal_Bow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Royal_Greatsword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Royal_Greatsword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Royal_Grimoire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Royal_Grimoire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Royal_Longsword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Royal_Longsword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Royal_Spear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Royal_Spear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Rust() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Rust", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Sacrificial_Bow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Sacrificial_Bow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Sacrificial_Fragments() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Sacrificial_Fragments", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Sacrificial_Greatsword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Sacrificial_Greatsword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Sacrificial_Sword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Sacrificial_Sword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Serpent_Spine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Serpent_Spine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Skyward_Atlas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Skyward_Atlas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Skyward_Blade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Skyward_Blade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Skyward_Harp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Skyward_Harp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Skyward_Pride() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Skyward_Pride", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Skyward_Spine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Skyward_Spine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Snow_Tombed_Starsilver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Snow_Tombed_Starsilver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Solar_Pearl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Solar_Pearl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Summit_Shaper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Summit_Shaper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Sword_of_Descension() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Sword_of_Descension", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_The_Bell() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_The_Bell", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_The_Black_Sword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_The_Black_Sword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_The_Flute() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_The_Flute", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_The_Stringless() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_The_Stringless", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_The_Unforged() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_The_Unforged", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_The_Viridescent_Hunt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_The_Viridescent_Hunt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_The_Widsith() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_The_Widsith", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Vortex_Vanquisher() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Vortex_Vanquisher", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Whiteblind() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Whiteblind", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Wolf_s_Gravestone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Wolf_s_Gravestone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
