'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Akashic_Records_of_Teyvat.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Element_Anemo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Element_Anemo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Element_Cryo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Element_Cryo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Element_Dendro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Element_Dendro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Element_Electro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Element_Electro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Element_Geo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Element_Geo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Element_Hydro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Element_Hydro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Element_Pyro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Element_Pyro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Image_Transparent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Image_Transparent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_Albedo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_Albedo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_Amber() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_Amber", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_barbra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_barbra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_Beidou() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_Beidou", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_Bennet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_Bennet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_Chongyun() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_Chongyun", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_Diluc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_Diluc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_Diona() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_Diona", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_Fischl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_Fischl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_Ganyu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_Ganyu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_Jean() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_Jean", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_Keaya() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_Keaya", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_Keqing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_Keqing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_Klee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_Klee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_Lisa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_Lisa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_mcF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_mcF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_mcM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_mcM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_Mona() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_Mona", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_Ningguang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_Ningguang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_Noelle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_Noelle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_QiQi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_QiQi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_Razor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_Razor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_Sucrose() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_Sucrose", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_Tartaglia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_Tartaglia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_Venti() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_Venti", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_Xaio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_Xaio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_XiangLing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_XiangLing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_Xinqui() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_Xinqui", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_Xinyan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_Xinyan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portBig_Zhongli() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portBig_Zhongli", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_Albedo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_Albedo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_Amber() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_Amber", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_Barbra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_Barbra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_Beidou() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_Beidou", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_Bennet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_Bennet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_Chongyun() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_Chongyun", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_Diluc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_Diluc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_Diona() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_Diona", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_Fischl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_Fischl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_Ganyu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_Ganyu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_Jean() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_Jean", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_Keaya() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_Keaya", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_Keqing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_Keqing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_Klee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_Klee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_Lisa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_Lisa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_McF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_McF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_McM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_McM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_Mona() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_Mona", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_Ningguang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_Ningguang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_Noelle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_Noelle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_QiQi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_QiQi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_Razor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_Razor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_Sucrose() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_Sucrose", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_Tartaglia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_Tartaglia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_Venti() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_Venti", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_XiangLing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_XiangLing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_Xinqui() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_Xinqui", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_Xinyan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_Xinyan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portSmall_Zhongli() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portSmall_Zhongli", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Random_Item_Adventurer_s_Experience() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Random_Item_Adventurer_s_Experience", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Random_Item_Hero_s_Wit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Random_Item_Hero_s_Wit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Random_Item_Intertwined_Fate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Random_Item_Intertwined_Fate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Random_Item_Primogem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Random_Item_Primogem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Random_Item_Wanderer_s_Advice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Random_Item_Wanderer_s_Advice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Random_Liyue_Reputation_EXP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Random_Liyue_Reputation_EXP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Random_Mondstadt_Reputation_EXP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Random_Mondstadt_Reputation_EXP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Amos_Bow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Amos_Bow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Aquila_Favonia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Aquila_Favonia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Blackcliff_Agate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Blackcliff_Agate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Blackcliff_Longsword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Blackcliff_Longsword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Blackcliff_Pole() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Blackcliff_Pole", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Blackcliff_Slasher() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Blackcliff_Slasher", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Blackcliff_Warbow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Blackcliff_Warbow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Compound_Bow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Compound_Bow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Crescent_Pike() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Crescent_Pike", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Deathmatch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Deathmatch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Dragon_s_Bane() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Dragon_s_Bane", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Dragonspine_Spear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Dragonspine_Spear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Eye_of_Perception() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Eye_of_Perception", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Favonius_Codex() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Favonius_Codex", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Favonius_Greatsword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Favonius_Greatsword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Favonius_Lance() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Favonius_Lance", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Favonius_Sword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Favonius_Sword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Favonius_Warbow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Favonius_Warbow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Festering_Desire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Festering_Desire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Frostbearer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Frostbearer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Iron_Sting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Iron_Sting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Lion_s_Roar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Lion_s_Roar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Lost_Prayer_to_the_Sacred_Winds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Lost_Prayer_to_the_Sacred_Winds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Mappa_Mare() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Mappa_Mare", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Memory_of_Dust() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Memory_of_Dust", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Primordial_Jade_Winged_Spear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Primordial_Jade_Winged_Spear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Prototype_Amber() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Prototype_Amber", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Prototype_Archaic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Prototype_Archaic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Prototype_Crescent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Prototype_Crescent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Prototype_Rancour() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Prototype_Rancour", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Prototype_Starglitter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Prototype_Starglitter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Rainslasher() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Rainslasher", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Royal_Bow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Royal_Bow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Royal_Greatsword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Royal_Greatsword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Royal_Grimoire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Royal_Grimoire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Royal_Longsword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Royal_Longsword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Royal_Spear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Royal_Spear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Rust() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Rust", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Sacrificial_Bow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Sacrificial_Bow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Sacrificial_Fragments() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Sacrificial_Fragments", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Sacrificial_Greatsword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Sacrificial_Greatsword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Sacrificial_Sword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Sacrificial_Sword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Serpent_Spine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Serpent_Spine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Skyward_Atlas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Skyward_Atlas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Skyward_Blade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Skyward_Blade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Skyward_Harp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Skyward_Harp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Skyward_Pride() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Skyward_Pride", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Skyward_Spine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Skyward_Spine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Snow_Tombed_Starsilver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Snow_Tombed_Starsilver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Solar_Pearl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Solar_Pearl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Summit_Shaper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Summit_Shaper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Sword_of_Descension() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Sword_of_Descension", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_The_Bell() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_The_Bell", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_The_Black_Sword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_The_Black_Sword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_The_Flute() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_The_Flute", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_The_Stringless() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_The_Stringless", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_The_Unforged() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_The_Unforged", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_The_Viridescent_Hunt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_The_Viridescent_Hunt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_The_Widsith() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_The_Widsith", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Vortex_Vanquisher() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Vortex_Vanquisher", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Whiteblind() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Whiteblind", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Weapon_Wolf_s_Gravestone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Weapon_Wolf_s_Gravestone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
